use incremental;
\! echo 'deleting obsolete incremental records';
delete from incremental.accesslogs where accesstime>now() or accesstime <= (select max(accesstime) from ocadmin_dbo.accesslogs where accesstime<now());
delete from incremental.admin where updatetime>now() or updatetime <= (select max(updatetime) from ocadmin_dbo.admin where updatetime<now());
delete from incremental.adminprivate where updatetime>now() or updatetime <= (select max(updatetime) from ocadmin_dbo.adminprivate where updatetime<now());
delete from incremental.items where transactionid in (select transactionid from transactions where ts>now() or ts<=(select max(ts) from openclinic_dbo.transactions where ts<now()));
delete from incremental.itemshistory where transactionid in (select transactionid from transactionshistory where ts>now() or ts<=(select max(ts) from openclinic_dbo.transactionshistory where ts<now()));
delete from incremental.oc_batchoperations where oc_batchoperation_updatetime>now() or oc_batchoperation_updatetime<= (select max(oc_batchoperation_updatetime) from openclinic_dbo.oc_batchoperations where oc_batchoperation_updatetime<now());
delete from incremental.oc_debets where oc_debet_updatetime>now() or oc_debet_updatetime<= (select max(oc_debet_updatetime) from openclinic_dbo.oc_debets where oc_debet_updatetime<now());
delete from incremental.oc_debets_history where oc_debet_updatetime>now() or oc_debet_updatetime<= (select max(oc_debet_updatetime) from openclinic_dbo.oc_debets_history where oc_debet_updatetime<now());
delete from incremental.oc_encounters where oc_encounter_updatetime>now() or oc_encounter_updatetime<= (select max(oc_encounter_updatetime) from openclinic_dbo.oc_encounters where oc_encounter_updatetime<now());
delete from incremental.oc_encounters_history where oc_encounter_updatetime>now() or oc_encounter_updatetime<= (select max(oc_encounter_updatetime) from openclinic_dbo.oc_encounters_history where oc_encounter_updatetime<now());
delete from incremental.oc_insurances where oc_insurance_updatetime>now() or oc_insurance_updatetime<= (select max(oc_insurance_updatetime) from openclinic_dbo.oc_insurances where oc_insurance_updatetime<now());
delete from incremental.oc_insurances_history where oc_insurance_updatetime>now() or oc_insurance_updatetime<= (select max(oc_insurance_updatetime) from openclinic_dbo.oc_insurances_history where oc_insurance_updatetime<now());
delete from incremental.oc_pacs where oc_pacs_updatetime>now() or oc_pacs_updatetime<= (select max(oc_pacs_updatetime) from openclinic_dbo.oc_pacs where oc_pacs_updatetime<now());
delete from incremental.oc_patientcredits where oc_patientcredit_updatetime>now() or oc_patientcredit_updatetime<= (select max(oc_patientcredit_updatetime) from openclinic_dbo.oc_patientcredits where oc_patientcredit_updatetime<now());
delete from incremental.oc_patientinvoices where oc_patientinvoice_updatetime>now() or oc_patientinvoice_updatetime<= (select max(oc_patientinvoice_updatetime) from openclinic_dbo.oc_patientinvoices where oc_patientinvoice_updatetime<now());
delete from incremental.oc_patientinvoices_history where oc_patientinvoice_updatetime>now() or oc_patientinvoice_updatetime<= (select max(oc_patientinvoice_updatetime) from openclinic_dbo.oc_patientinvoices_history where oc_patientinvoice_updatetime<now());
delete from incremental.oc_productstocks_history where oc_stock_updatetime>now() or oc_stock_updatetime<= (select max(oc_stock_updatetime) from openclinic_dbo.oc_productstocks_history where oc_stock_updatetime<now());
delete from incremental.oc_productstockoperations where oc_operation_updatetime>now() or oc_operation_updatetime<= (select max(oc_operation_updatetime) from openclinic_dbo.oc_productstockoperations where oc_operation_updatetime<now());
delete from incremental.oc_wicket_credits where oc_wicket_credit_updatetime>now() or oc_wicket_credit_updatetime<= (select max(oc_wicket_credit_updatetime) from openclinic_dbo.oc_wicket_credits where oc_wicket_credit_updatetime<now());
delete from incremental.requestedlabanalyses where updatetime>now() or updatetime<= (select max(updatetime) from openclinic_dbo.requestedlabanalyses where updatetime<now());
delete from incremental.transactions where ts>now() or ts<= (select max(ts) from openclinic_dbo.transactions where ts<now());
delete from incremental.transactionshistory where ts>now() or ts<= (select max(ts) from openclinic_dbo.transactionshistory where ts<now());
\! echo 'merging accesslogs';
insert into ocadmin_dbo.accesslogs select * from incremental.accesslogs where accesstime<now();
\! echo 'merging admin';
delete from ocadmin_dbo.admin using ocadmin_dbo.admin,incremental.admin where ocadmin_dbo.admin.personid=incremental.admin.personid;
insert into ocadmin_dbo.admin select * from incremental.admin where updatetime<now();
\! echo 'merging adminprivate';
delete from ocadmin_dbo.adminprivate using ocadmin_dbo.adminprivate,incremental.adminprivate where ocadmin_dbo.adminprivate.privateid=incremental.adminprivate.privateid;
insert into ocadmin_dbo.adminprivate select * from incremental.adminprivate where updatetime<now();
\! echo 'merging items';
delete from openclinic_dbo.items using openclinic_dbo.items,incremental.items where openclinic_dbo.items.serverid=incremental.items.serverid and openclinic_dbo.items.itemid=incremental.items.itemid;
insert into openclinic_dbo.items select * from incremental.items;
insert into openclinic_dbo.itemshistory select * from incremental.itemshistory where transactionid in (select transactionid from incremental.transactionshistory where ts<now());
\! echo 'merging oc_batchoperations';
delete from openclinic_dbo.oc_batchoperations using openclinic_dbo.oc_batchoperations,incremental.oc_batchoperations where incremental.oc_batchoperations.oc_batchoperation_productstockoperationuid=openclinic_dbo.oc_batchoperations.oc_batchoperation_productstockoperationuid and incremental.oc_batchoperations.oc_batchoperation_sourceuid=openclinic_dbo.oc_batchoperations.oc_batchoperation_sourceuid and incremental.oc_batchoperations.oc_batchoperation_destinationuid=openclinic_dbo.oc_batchoperations.oc_batchoperation_destinationuid;
insert into openclinic_dbo.oc_batchoperations select * from incremental.oc_batchoperations where oc_batchoperation_updatetime<now();
\! echo 'merging oc_debets';
delete from openclinic_dbo.oc_debets using openclinic_dbo.oc_debets,incremental.oc_debets where openclinic_dbo.oc_debets.oc_debet_serverid=incremental.oc_debets.oc_debet_serverid and openclinic_dbo.oc_debets.oc_debet_objectid=incremental.oc_debets.oc_debet_objectid;
insert into openclinic_dbo.oc_debets select * from incremental.oc_debets where oc_debet_updatetime<now();
insert into openclinic_dbo.oc_debets_history select * from incremental.oc_debets_history where oc_debet_updatetime<now();
\! echo 'merging oc_encounters';
delete from openclinic_dbo.oc_encounters using openclinic_dbo.oc_encounters,incremental.oc_encounters where openclinic_dbo.oc_encounters.oc_encounter_serverid=incremental.oc_encounters.oc_encounter_serverid and openclinic_dbo.oc_encounters.oc_encounter_objectid=incremental.oc_encounters.oc_encounter_objectid;
insert into openclinic_dbo.oc_encounters select * from incremental.oc_encounters where oc_encounter_updatetime<now();
insert into openclinic_dbo.oc_encounters_history select * from incremental.oc_encounters_history where oc_encounter_updatetime<now();
\! echo 'merging oc_insurances';
delete from openclinic_dbo.oc_insurances using openclinic_dbo.oc_insurances,incremental.oc_insurances where openclinic_dbo.oc_insurances.oc_insurance_serverid=incremental.oc_insurances.oc_insurance_serverid and openclinic_dbo.oc_insurances.oc_insurance_objectid=incremental.oc_insurances.oc_insurance_objectid;
insert into openclinic_dbo.oc_insurances select * from incremental.oc_insurances where oc_insurance_updatetime<now();
insert into openclinic_dbo.oc_insurances_history select * from incremental.oc_insurances_history where oc_insurance_updatetime<now();
\! echo 'merging oc_pacs';
delete from openclinic_dbo.oc_pacs using openclinic_dbo.oc_pacs,incremental.oc_pacs where openclinic_dbo.oc_pacs.oc_pacs_studyuid=incremental.oc_pacs.oc_pacs_studyuid and openclinic_dbo.oc_pacs.oc_pacs_series=incremental.oc_pacs.oc_pacs_series;insert into openclinic_dbo.oc_pacs select * from incremental.oc_pacs where oc_pacs_updatetime<now();
\! echo 'merging oc_patientcredits';
delete from openclinic_dbo.oc_patientcredits using openclinic_dbo.oc_patientcredits,incremental.oc_patientcredits where openclinic_dbo.oc_patientcredits.oc_patientcredit_serverid=incremental.oc_patientcredits.oc_patientcredit_serverid and openclinic_dbo.oc_patientcredits.oc_patientcredit_objectid=incremental.oc_patientcredits.oc_patientcredit_objectid;
insert into openclinic_dbo.oc_patientcredits select * from incremental.oc_patientcredits where oc_patientcredit_updatetime<now();
\! echo 'merging oc_patientinvoices';
delete from openclinic_dbo.oc_patientinvoices using openclinic_dbo.oc_patientinvoices,incremental.oc_patientinvoices where openclinic_dbo.oc_patientinvoices.oc_patientinvoice_serverid=incremental.oc_patientinvoices.oc_patientinvoice_serverid and openclinic_dbo.oc_patientinvoices.oc_patientinvoice_objectid=incremental.oc_patientinvoices.oc_patientinvoice_objectid;
insert into openclinic_dbo.oc_patientinvoices select * from incremental.oc_patientinvoices where oc_patientinvoice_updatetime<now();
insert into openclinic_dbo.oc_patientinvoices_history select * from incremental.oc_patientinvoices_history where oc_patientinvoice_updatetime<now();
\! echo 'merging oc_productstocks_history';
insert into openclinic_dbo.oc_productstocks_history select * from incremental.oc_productstocks_history where oc_stock_updatetime<now();
\! echo 'merging oc_productstockoperations';
delete from openclinic_dbo.oc_productstockoperations using openclinic_dbo.oc_productstockoperations,incremental.oc_productstockoperations where openclinic_dbo.oc_productstockoperations.oc_operation_serverid=incremental.oc_productstockoperations.oc_operation_serverid and openclinic_dbo.oc_productstockoperations.oc_operation_objectid=incremental.oc_productstockoperations.oc_operation_objectid;
insert into openclinic_dbo.oc_productstockoperations select * from incremental.oc_productstockoperations where oc_operation_updatetime<now();
\! echo 'merging oc_wicket_credits';
delete from openclinic_dbo.oc_wicket_credits using openclinic_dbo.oc_wicket_credits,incremental.oc_wicket_credits where openclinic_dbo.oc_wicket_credits.oc_wicket_credit_serverid=incremental.oc_wicket_credits.oc_wicket_credit_serverid and openclinic_dbo.oc_wicket_credits.oc_wicket_credit_objectid=incremental.oc_wicket_credits.oc_wicket_credit_objectid;
insert into openclinic_dbo.oc_wicket_credits select * from incremental.oc_wicket_credits where oc_wicket_credit_updatetime<now();
\! echo 'merging requestedlabanalyses';
delete from openclinic_dbo.requestedlabanalyses using openclinic_dbo.requestedlabanalyses,incremental.requestedlabanalyses where incremental.requestedlabanalyses.transactionid=openclinic_dbo.requestedlabanalyses.transactionid and incremental.requestedlabanalyses.analysiscode=openclinic_dbo.requestedlabanalyses.analysiscode;
insert into openclinic_dbo.requestedlabanalyses select * from incremental.requestedlabanalyses where updatetime<now();
\! echo 'merging transactions';
delete from openclinic_dbo.transactions using openclinic_dbo.transactions,incremental.transactions where openclinic_dbo.transactions.serverid=incremental.transactions.serverid and openclinic_dbo.transactions.transactionid=incremental.transactions.transactionid;
insert into openclinic_dbo.transactions select * from incremental.transactions where ts<now();
insert into openclinic_dbo.transactionshistory select * from incremental.transactionshistory where ts<now();
